### ISSUE TITLE
Synchronous implementation of pbkdf2

### ISSUE THREAD

**Issue by adilmezghouti** [ex3ndr/react-native-pbkdf2#2]
I would like to contribute a synchronous implementation of pbkdf2 that can be used with react-native-crypto for example.

**Comment by ex3ndr** [comment]
Hello, there are a new library in the wild I think it is way superior than anything else! 
https://github.com/margelo/react-native-quick-crypto

**Comment by adilmezghouti** [comment]
Hi. I agree. It just got released by Margelo. Thanks.
